cleanup
BIBSYSDEV/marc-presentation pull request #243
Opened 2022-04-04 07:35 UTC by pcb-unit

2022-04-04 08:14 UTC, anetteOlli requested changes

2022-04-04 08:14 UTC, anetteOlli commented on src/index.tsx
> +if (container) {
if (!container) throw new Error('Failed to find the root element');
Så kan resten av if-blokka flates ut

2022-04-04 09:23 UTC, pcb-unit commented on src/index.tsx
> +if (container) {
det var da svært så ordentlig vi skal ha det da :-P:-)
Fikset

2022-04-04 09:23 UTC, pcb-unit commented
Kjørte også en audit fix og fikk ryddet bort litt snusk i package-lock-filen

2022-04-19 06:46 UTC, anetteOlli approved these changes

2022-04-19 06:50 UTC, merged