Smile 328 download as file
BIBSYSDEV/marc-presentation pull request #5
Opened 2021-01-11 07:59 UTC by nraanes

2021-01-11 11:23 UTC, pcb-unit commented on src/components/DataDownload.tsx
> +    const [xmlContent, setXmlContent] = useState<string>("");
trenger ikke <string> når den er initiert som string

2021-01-11 11:24 UTC, pcb-unit commented on src/components/DataDownload.tsx
> +    const [lineContent, setLineContent] = useState<string>("");
same

2021-01-11 11:30 UTC, pcb-unit requested changes

2021-01-11 11:30 UTC, pcb-unit commented on src/components/DataDownload.tsx
> +const DataDownload: FC = (props: any) => {
kan destrukturere og skrive `{marcdata}` istenfor props

2021-01-11 11:30 UTC, pcb-unit commented on src/components/DataDownload.tsx
> +const DataDownload: FC = (props: any) => {
og helst ha med typer - unngå any

2021-01-11 11:30 UTC, pcb-unit commented on src/components/DataDownload.tsx
> +        let blob = new Blob([content], {type: mimetype});
helst bruke konst der det kan brukes

2021-01-11 11:30 UTC, pcb-unit commented on src/components/DataDownload.tsx
> +    function createDownload(content: string, filename: string, mimetype: string) {
finnes det ikke andre måter å tvinge fram nedlasting enn å opprette en lenke og slette den ?

2021-01-11 11:30 UTC, pcb-unit commented on src/components/DataDownload.tsx
> +                color={"default"}
tror ikke klammer en nødvendig. Er ikke dessuten default default ?

2021-01-12 07:51 UTC, gregorgabriel approved these changes

2021-01-18 08:50 UTC, nraanes commented on src/components/DataDownload.tsx
> +const DataDownload: FC = (props: any) => {
Ingrid har fikset :)

2021-01-18 08:54 UTC, nraanes commented on src/components/DataDownload.tsx
> +                color={"default"}
Godt poeng!

2021-01-18 09:00 UTC, nraanes commented on src/components/DataDownload.tsx
> +    function createDownload(content: string, filename: string, mimetype: string) {
Finnes libs, men virker som denne løsningen er ganske populær og fungerer i "alle" browsere.

2021-01-18 09:13 UTC, pcb-unit commented on src/components/DataDownload.tsx
> +            setXmlContent(marcData.xmlPresentation ? marcData.xmlPresentation : "");
kan skrives `marcData.xmlPresentation ?? ""`

2021-01-18 09:15 UTC, pcb-unit commented on src/components/DataDownload.tsx
> +        if (marcData) {
er det ikke bedre å ta sjekken på if (marcdata) rundt DataDownload-elementet ? da slipper man optional på props også

2021-01-19 09:36 UTC, nraanes commented on src/components/DataDownload.tsx
> +        if (marcData) {
Betyr det å sette en if i "parenten" (App.tsx) sin return som tar i bruk DataDownload, slik at den kun rendres (er det riktig bruk av ordet?) dersom marcdata er tilstede?

2021-01-19 09:37 UTC, pcb-unit commented on src/components/DataDownload.tsx
> +        if (marcData) {
jepp. men samkjør med Eirik, han driver med samme kode :-)

2021-01-21 12:02 UTC, nraanes commented
Jo, venter på å få merget inn formateringen først. Ideelt sett burde download merges inn også mtp. på styling, også fikse på marcdata etterpå.

2021-01-21 12:04 UTC, pcb-unit approved these changes

2021-01-22 11:56 UTC, pcb-unit approved these changes

2021-01-22 13:22 UTC, Eirik-Eide-Saur approved these changes

2021-01-25 08:06 UTC, merged